### ISSUE TITLE
Wellcomeml ml imports broken

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#217]
In the latest master, but not in the latest release, after merging #203, imports of any WellcomeML module are broken because `hdbscan` is missing. There are two problems here:

- We do not throw the useful message to the user that we designed, because this is thrown when a user imports explicitly the clustering module
- The intended change was not suppose to affect other modules, the intended behaviour was for the error to be thrown only if a user tries to import the clustering class

```
>>> from wellcomeml.ml import CNNClassifier
2021-02-16 20:38:00 wellcomeml.logger ERROR: No module named 'hdbscan'
2021-02-16 20:38:00 wellcomeml.logger WARNING: Using WellcomeML without extras (transformers & torch).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CNNClassifier' from 'wellcomeml.ml' (/Users/emiliahadjikyriakou/code/test/WellcomeML/wellcomeml/ml/__init__.py)
```

**Comment by nsorros** [comment]
Turns out that the exception that needs to be caught is `ModuleNotFoundError`. See below

```
>>> import wellcomeml.ml.clustering
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/wellcomeml/ml/__init__.py", line 4, in <module>
    from .frequency_vectorizer import WellcomeTfidf
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/wellcomeml/ml/frequency_vectorizer.py", line 10, in <module>
    import spacy
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.api import prefer_gpu, require_gpu, require_cpu  # noqa: F401
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/thinc/api.py", line 2, in <module>
    from .initializers import normal_init, uniform_init, glorot_uniform_init, zero_init
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/thinc/initializers.py", line 4, in <module>
    from .backends import Ops
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/thinc/backends/__init__.py", line 7, in <module>
    from .cupy_ops import CupyOps, has_cupy
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/thinc/backends/cupy_ops.py", line 18, in <module>
    from .numpy_ops import NumpyOps
from collections import defaultdict
  File "thinc/backends/numpy_ops.pyx", line 1, in init thinc.backends.numpy_ops
  File "<frozen importlib._bootstrap>", line 416, in parent
KeyboardInterrupt
>>> from wellcomeml.ml import CNNClassifier
2021-02-17 10:48:23 wellcomeml.logger ERROR: No module named 'hdbscan'
2021-02-17 10:48:23 wellcomeml.logger WARNING: Using WellcomeML without extras (transformers & torch).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CNNClassifier' from 'wellcomeml.ml' (/Users/nsorros/code/test/venv/lib/python3.7/site-packages/wellcomeml/ml/__init__.py)
>>> from wellcomeml.ml.cluster import TextClustering
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wellcomeml.ml.cluster'
>>> from wellcomeml.ml.clustering import TextClustering
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nsorros/code/test/venv/lib/python3.7/site-packages/wellcomeml/ml/clustering.py", line 16, in <module>
    from hdbscan import HDBSCAN
ModuleNotFoundError: No module named 'hdbscan'
```
