### PR TITLE
Fix error caught when hdbscan is missing

### LINKED ISSUE #217: Wellcomeml ml imports broken
In the latest master, but not in the latest release, after merging #203, imports of any WellcomeML module are broken because `hdbscan` is missing. There are two problems here:

- We do not throw the useful message to the user that we designed, because this is thrown when a user imports explicitly the clustering module
- The intended change was not suppose to affect other modules, the intended behaviour was for the error to be thrown only if a user tries to import the clustering class

```
>>> from wellcomeml.ml import CNNClassifier
2021-02-16 20:38:00 wellcomeml.logger ERROR: No module named 'hdbscan'
2021-02-16 20:38:00 wellcomeml.logger WARNING: Using WellcomeML without extras (transformers & torch).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'CNNClassifier' from 'wellcomeml.ml' (/Users/emiliahadjikyriakou/code/test/WellcomeML/wellcomeml/ml/__init__.py)
```

### PR DESCRIPTION
**Pull request by nsorros**
Description
---

Fixes #217

Essentially we were catching a `ValueError` instead of `ModuleNotFoundError`

Checklist
---

- [x] Added link to Github issue or Trello card
- [ ] Added tests

### CODE REVIEW

File: wellcomeml/ml/clustering.py [hunk 1]
```diff
@@ -15,7 +15,7 @@
 try:
     from hdbscan import HDBSCAN
     HDBSCAN_INSTALLED = True
-except ValueError:
+except ModuleNotFoundError:
```
Comment (aCampello) [inline wellcomeml/ml/clustering.py:18]: I think we need to catch both errors actually.

If hdbscan is installed (but not installed with the right flags), it will still throw a value error as per https://github.com/wellcometrust/WellcomeML/issues/197. 

So maybe `except (ValueError, ModuleNotFoundError)`.

**Review by aCampello — CHANGES_REQUESTED** [review]

File: wellcomeml/ml/clustering.py (hunk 1 above)
Comment (nsorros) [reply wellcomeml/ml/clustering.py]: 394062a

**Review by aCampello — APPROVED** [review]
